#!/usr/bin/env bun
/**
 * Rank every corpus surface form still missing a gloss and/or display POS,
 * by occurrence, with a context sample — the worklist for closing the
 * remaining morph_gloss coverage gap.
 *
 *   bun scripts/report_gloss_gaps.mjs        # → build/gloss-gaps.md
 *
 * Requires build/corpus.db with morph_gloss loaded (see load_tokens.mjs).
 */
import { Database } from "bun:sqlite";
import { writeFileSync } from "node:fs";

const DB = new URL("../build/corpus.db", import.meta.url).pathname;
const OUT = new URL("../build/gloss-gaps.md", import.meta.url).pathname;
const TOP = Number(process.argv.find((a) => a.startsWith("--top="))?.slice(6) ?? 200);

const db = new Database(DB, { readonly: true });

const cov = db.query(`
  WITH wl AS (
    SELECT t.surface_fold f, t.upos, mg.gloss_en, mg.pos_display
    FROM corpus_tokens t LEFT JOIN morph_gloss mg ON mg.key_fold = t.surface_fold
    WHERE t.surface_fold GLOB '*[a-z]*' AND coalesce(t.upos,'') <> 'PUNCT')
  SELECT count(*) tokens,
    round(100.0*sum(gloss_en IS NOT NULL)/count(*),2) gloss_pct,
    round(100.0*sum(coalesce(pos_display,upos) IS NOT NULL AND coalesce(pos_display,upos)<>'')/count(*),2) pos_pct
  FROM wl`).get();

const gaps = db.query(`
  SELECT t.surface_fold fold, min(t.surface_norm) sample,
         min(coalesce(t.upos,'')) upos, count(*) c,
         max(mg.gloss_en IS NOT NULL) has_gloss,
         max(coalesce(mg.pos_display, t.upos, '') <> '') has_pos
  FROM corpus_tokens t LEFT JOIN morph_gloss mg ON mg.key_fold = t.surface_fold
  WHERE t.surface_fold GLOB '*[a-z]*' AND coalesce(t.upos,'') <> 'PUNCT'
    AND (mg.gloss_en IS NULL OR coalesce(mg.pos_display, t.upos, '') = '')
  GROUP BY t.surface_fold ORDER BY c DESC LIMIT ?`).all(TOP);

const ctxStmt = db.prepare(`
  SELECT substr(s.text, max(1, t.char_start-30), 70) x
  FROM corpus_tokens t JOIN sentences s ON s.id = t.sentence_id
  WHERE t.surface_fold = ? LIMIT 1`);

const lines = [
  `# morph_gloss coverage gaps`,
  ``,
  `Generated by \`bun scripts/report_gloss_gaps.mjs\` — re-run after any gloss rebuild.`,
  ``,
  `**Coverage:** gloss ${cov.gloss_pct}% · POS ${cov.pos_pct}% over ${cov.tokens} word-like tokens.`,
  ``,
  `| # | fold | occ | missing | UPOS | context |`,
  `|--:|------|----:|---------|------|---------|`,
];
gaps.forEach((g, i) => {
  const miss = [!g.has_gloss && "gloss", !g.has_pos && "pos"].filter(Boolean).join("+");
  const ctx = (ctxStmt.get(g.fold)?.x ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
  lines.push(`| ${i + 1} | \`${g.fold}\` | ${g.c} | ${miss} | ${g.upos || "—"} | ${ctx} |`);
});
writeFileSync(OUT, lines.join("\n") + "\n");
console.log(`coverage: gloss ${cov.gloss_pct}%  pos ${cov.pos_pct}%`);
console.log(`top ${gaps.length} gaps -> ${OUT}`);
